### ISSUE TITLE
Website style refactoring

### ISSUE THREAD

**Issue by jayalaves** [AutarkLabs/autark-design#43]
**Background**
Refine the styles on the website to reduce total number of styles needed and increase reusability across pages.

**To-dos**
- [x] Navigation bar
- [x] Large video header
- [x] Large text description
- [x] Large text description with button
- [x] Team columns section
- [x] Large blogpost item
- [x] Small blogpost item
- [x] Footer section
- [x] Medium header
- [x] Text section
