### ISSUE TITLE
Provide feedback and design direction on Sprint 19.17 tickets

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/autark-design#7]
- [x] https://github.com/AutarkLabs/planning-suite/issues/1023 [Projects Overview - Design Review]
- [x] https://github.com/AutarkLabs/planning-suite/issues/932 [Projects - Issue curation - Design Review]
- [x] https://github.com/AutarkLabs/planning-suite/issues/754 [Projects filter bar - respond to my comment w/ the new suggestion]
- [x] https://github.com/AutarkLabs/planning-suite/issues/944 [Projects filter bar - closed issues/PRs]
- [x] https://github.com/AutarkLabs/planning-suite/issues/1005 [Sort design pattern]
- [x] https://github.com/AutarkLabs/planning-suite/issues/996 [Address Book badge color, re: discussion in Loomio]
